/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantePOS;

import java.sql.Connection;
import java.sql.Date;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.DateFormat;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Cliente;
import models.Produtos;
import models.Reservas;
import net.proteanit.sql.DbUtils;
import util.DBConnector;

/**
 *
 * @author Mr.Belton
 */
public class JIFReservas extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFReservas
     */
    private PreparedStatement pstm = null;
    private Connection con = null;
    private ResultSet rs = null;
    private Statement st;
    ArrayList<Cliente> listaClientes = null;
    
    public JIFReservas() {
        super("Gestao de reservas");
        initComponents();
        setClosable(true);
        conectar();
        listarReservas();
        jDateData.setDate(Calendar.getInstance().getTime());
        
        listaClientes = (ArrayList<Cliente>) DBConnector.buscarTodos(Cliente.class);
        
        jComboClientes.addItem("Outro");
        
         for(int i=0; i<listaClientes.size(); i++){
            jComboClientes.addItem(listaClientes.get(i).getNome());
        }
        
    }
    
    public void conectar(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sgrestaurante","root","");
          st=con.createStatement();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
     }

    
    public void listarReservas(){
        String sql= "Select idReservas, nomeCliente, telefone, data, horarioInicial, horarioFinal from reservas";
        try {
            pstm = con.prepareStatement(sql);
            rs = pstm.executeQuery();
            tableReservas.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(JIFClientes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

 
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        dateUtil1 = new com.toedter.calendar.DateUtil();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        txtTelefone = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtNomeCliente = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        txtNrIdentificacao = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jComboClientes = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jComboTipoID = new javax.swing.JComboBox();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jDateData = new com.toedter.calendar.JDateChooser();
        jLabel4 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jSpinnerAcompanhantes = new javax.swing.JSpinner();
        jLabel12 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTimeHoraInicial = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jLabel15 = new javax.swing.JLabel();
        jTimeHoraFinal = new lu.tudor.santec.jtimechooser.JTimeChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        txtObservacoes = new javax.swing.JTextArea();
        jLabel11 = new javax.swing.JLabel();
        jSpinnerMesasOcupadas = new javax.swing.JSpinner();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableReservas = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel16 = new javax.swing.JLabel();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();

        setClosable(true);
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registrar reserva"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Informacoes do cliente"));

        jLabel2.setText("Telefone");

        jLabel1.setText("Nome do cliente");

        jLabel14.setText("Numero");

        txtNrIdentificacao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNrIdentificacaoActionPerformed(evt);
            }
        });

        jLabel5.setText("Clientes registrados");

        jComboClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboClientesActionPerformed(evt);
            }
        });

        jLabel6.setText("Cell.");

        jLabel7.setText("Tipo de identificacao");

        jComboTipoID.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "BI", "Passaporte", "DIR" }));
        jComboTipoID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboTipoIDActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel7))
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtNomeCliente))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(4, 4, 4)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel6)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtCelular))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jComboTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 23, Short.MAX_VALUE)
                                        .addComponent(jLabel14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNrIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboClientes, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jComboClientes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNomeCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNrIdentificacao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel7)
                    .addComponent(jComboTipoID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Detalhes da reserva"));

        jLabel3.setText("Data");

        jLabel4.setText("Horario:    das");

        jLabel9.setText("Nr de acompanhantes");

        jSpinnerAcompanhantes.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jLabel12.setText("Preco");

        jLabel13.setText("MT");

        jTimeHoraInicial.setShowSeconds(false);

        jLabel15.setText("as");

        jTimeHoraFinal.setShowSeconds(false);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jDateData, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerAcompanhantes, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTimeHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel15)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTimeHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel12)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabel13)))
                        .addGap(0, 0, Short.MAX_VALUE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jDateData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel9)
                        .addComponent(jSpinnerAcompanhantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(jTimeHoraInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel15)
                    .addComponent(jTimeHoraFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13))
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Outros detalhes"));

        jLabel10.setText("Observacoes");

        txtObservacoes.setColumns(20);
        txtObservacoes.setRows(5);
        jScrollPane2.setViewportView(txtObservacoes);

        jLabel11.setText("Nr de mesas a ocupar");

        jSpinnerMesasOcupadas.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSpinnerMesasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jLabel11)
                    .addComponent(jSpinnerMesasOcupadas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 76, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(5, 5, 5))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de reservas"));

        tableReservas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableReservas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableReservasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableReservas);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32))
        );

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton3.setText("Remover");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton2.setText("Limpar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jLabel16.setText("Pesquisa por Data");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton4)
                        .addGap(303, 303, 303)
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton1)
                        .addComponent(jButton2)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jLabel16))
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 234, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
           jButton1.setEnabled(true);
           jComboClientes.setSelectedItem("Outro");
           jComboTipoID.setEnabled(true);
                txtNomeCliente.setEnabled(true);
                txtCelular.setEnabled(true);
                txtTelefone.setEnabled(true);
                txtNrIdentificacao.setEnabled(true);
           txtCelular.setText("");
            txtNomeCliente.setText("");
            txtNrIdentificacao.setText("");
            txtObservacoes.setText("");
            txtPreco.setText("");
            txtTelefone.setText("");
            jDateData.setDate(Calendar.getInstance().getTime());
            jTimeHoraFinal.getTimeField().setText("00:00");
            jTimeHoraInicial.getTimeField().setText("00:00");
            jButton1.setEnabled(true);
            jSpinnerAcompanhantes.setValue(0);
            jSpinnerMesasOcupadas.setValue(0);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
      
        try {
            int idCliente =00;
            int idMorada =0;
            int idIdentificacao =0;
            String sql = "Select * from cliente where nome like ?";
            pstm = con.prepareStatement(sql);
            pstm.setString(1,txtNomeCliente.getText());
            rs = pstm.executeQuery();
            while(rs.next()){
                idCliente = rs.getInt("idCliente");
            }
            
            Cliente cliente = (Cliente) DBConnector.buscar(Cliente.class, idCliente);
            Reservas reservaN = new Reservas(null,txtNomeCliente.getText(),txtTelefone.getText(),txtCelular.getText(),jComboTipoID.getSelectedItem().toString(),txtNrIdentificacao.getText(),jDateData.getDate(),jTimeHoraInicial.getFormatedTime(), jTimeHoraFinal.getFormatedTime(),(int) jSpinnerAcompanhantes.getValue(), (int) jSpinnerMesasOcupadas.getValue(),txtObservacoes.getText(),Double.parseDouble(txtPreco.getText()));            
            Reservas reserva = new Reservas(cliente,txtNomeCliente.getText(),txtTelefone.getText(),txtCelular.getText(),jComboTipoID.getSelectedItem().toString(),txtNrIdentificacao.getText(),jDateData.getDate(),jTimeHoraInicial.getFormatedTime(), jTimeHoraFinal.getFormatedTime(),(int) jSpinnerAcompanhantes.getValue(), (int) jSpinnerMesasOcupadas.getValue(),txtObservacoes.getText(),Double.parseDouble(txtPreco.getText()));
            
            if(jComboClientes.getSelectedItem().equals("Outro"))
            DBConnector.salvar(reservaN);
            else
            DBConnector.salvar(reserva);
            listarReservas();
            txtCelular.setText("");
            txtNomeCliente.setText("");
            txtNrIdentificacao.setText("");
            txtObservacoes.setText("");
            txtPreco.setText("");
            txtTelefone.setText("");
            jDateData.setDate(Calendar.getInstance().getTime());
            jTimeHoraFinal.getTimeField().setText("00:00");
            jTimeHoraInicial.getTimeField().setText("00:00");
            jSpinnerAcompanhantes.setValue(0);
            jSpinnerMesasOcupadas.setValue(0);
            
            
        } catch (SQLException ex) {
            Logger.getLogger(JIFReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
     
 
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jComboClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboClientesActionPerformed
        try {
            txtNomeCliente.setEnabled(false);
            txtNomeCliente.setEnabled(false);
                txtCelular.setEnabled(false);
                txtTelefone.setEnabled(false);
                txtNrIdentificacao.setEnabled(false);
                jComboTipoID.setEnabled(false);
                
            if(jComboClientes.getSelectedItem().equals("Outro")){
                jComboTipoID.setEnabled(true);
                txtNomeCliente.setEnabled(true);
                txtCelular.setEnabled(true);
                txtTelefone.setEnabled(true);
                txtNrIdentificacao.setEnabled(true);
                txtCelular.setText("");
                txtTelefone.setText("");
                txtNrIdentificacao.setText("");
            }
            
            String clienteNome ="";
            int idContacto =0;
            int idIdentificacao =0;
            String sql = "Select * from cliente where nome like ?";
            pstm = con.prepareStatement(sql);
            pstm.setString(1,jComboClientes.getSelectedItem().toString());
            rs = pstm.executeQuery();
            while(rs.next()){
                clienteNome = rs.getString("nome");
                idContacto = rs.getInt("Contacto_idContacto");
                idIdentificacao = rs.getInt("Identificacao_idIdentificacao");
            }
            
            txtNomeCliente.setText(clienteNome);
            
            String tel ="";
            String cell ="";
            sql = "Select * from contacto where idContacto = ?";
            pstm = con.prepareStatement(sql);
            pstm.setInt(1,idContacto);
            rs = pstm.executeQuery();
            while(rs.next()){
                tel = rs.getString("telefone");
                cell = rs.getString("celular");
            }
           txtTelefone.setText(tel);
           txtCelular.setText(cell);
            
           String tipoID="";
           String numeroID ="";
           sql = "Select * from identificacao where idIdentificacao = ?";
            pstm = con.prepareStatement(sql);
            pstm.setInt(1,idIdentificacao);
            rs = pstm.executeQuery();
            while(rs.next()){
                tipoID = rs.getString("tipoIdentificacao");
                numeroID = rs.getString("numeroIdentificacao");
            }
           jComboTipoID.setSelectedItem(tipoID);
           txtNrIdentificacao.setText(numeroID);
           
           
        } catch (SQLException ex) {
            Logger.getLogger(JIFReservas.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jComboClientesActionPerformed

    private void jComboTipoIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboTipoIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboTipoIDActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
         if(tableReservas.getSelectedRow() == -1){
           JOptionPane.showMessageDialog(null,"Seleccione a reserva a ser removida","Atencao!",JOptionPane.WARNING_MESSAGE);
       }else{
           DBConnector.apagar(Reservas.class, (int) tableReservas.getValueAt(tableReservas.getSelectedRow(),0));
           listarReservas();
            jButton1.setEnabled(true);
            txtCelular.setText("");
            txtNomeCliente.setText("");
            txtNrIdentificacao.setText("");
            txtObservacoes.setText("");
            txtPreco.setText("");
            txtTelefone.setText("");
            jDateData.setDate(Calendar.getInstance().getTime());
            jTimeHoraFinal.getTimeField().setText("00:00");
            jTimeHoraInicial.getTimeField().setText("00:00");
            jButton1.setEnabled(true);
         }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void tableReservasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableReservasMouseClicked
     Reservas res = (Reservas) DBConnector.buscar(Reservas.class, (int) tableReservas.getValueAt(tableReservas.getSelectedRow(), 0));
     jButton1.setEnabled(false);
     Cliente cliente = new Cliente();
     if(res.getCliente().getIdCliente()!=00){
     cliente = (Cliente) DBConnector.buscar(Cliente.class, res.getCliente().getIdCliente());
     txtNomeCliente.setEnabled(false);
     txtNomeCliente.setEnabled(false);
     txtCelular.setEnabled(false);
     txtTelefone.setEnabled(false);
     txtNrIdentificacao.setEnabled(false);
     jComboTipoID.setEnabled(false);
     jComboClientes.setSelectedItem(res.getNomeCliente());
     }else{
     jComboClientes.setSelectedItem("Outro");
     txtNomeCliente.setText(res.getNomeCliente());
     txtCelular.setText(res.getCelular());
     txtNrIdentificacao.setText(res.getNumeroIdentificacao());
     txtTelefone.setText(res.getTelefone());
      jComboTipoID.setSelectedItem(res.getTipoIdentificacao());
     }
     txtObservacoes.setText(res.getObservacoes());
     txtPreco.setText(res.getPreco()+"");
     jTimeHoraInicial.getTimeField().setText(res.getHorarioInicial());
     jTimeHoraFinal.getTimeField().setText(res.getHorarioFinal());
     jDateData.setDate(res.getData());
     jSpinnerAcompanhantes.setValue(res.getNrAcompanhantes());
     
    }//GEN-LAST:event_tableReservasMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
       Reservas res = (Reservas) DBConnector.buscar(Reservas.class, (int) tableReservas.getValueAt(tableReservas.getSelectedRow(), 0));
       
       res.setCelular(txtCelular.getText());
       res.setData(jDateData.getDate());
       res.setHorarioFinal(jTimeHoraFinal.getTimeField().getText());
       res.setHorarioInicial(jTimeHoraInicial.getTimeField().getText());
       res.setNomeCliente(txtNomeCliente.getText());
       res.setNrAcompanhantes((int) jSpinnerAcompanhantes.getValue());
       res.setNrMesas((int) jSpinnerMesasOcupadas.getValue());
       res.setObservacoes(txtObservacoes.getText());
       res.setPreco(Double.parseDouble(txtPreco.getText()));
       
       if(jComboClientes.getSelectedItem().equals("Outro")){
           res.setCelular(txtCelular.getText());
           res.setTelefone(txtTelefone.getText());
           res.setNumeroIdentificacao(txtNrIdentificacao.getText());
           res.setTipoIdentificacao(jComboTipoID.getSelectedItem().toString());
       }else{
           
           try {
               String clienteNome ="";
               int Idcliente =0;
               int idContacto =0;
               int idIdentificacao =0;
               String sql = "Select * from cliente where nome like ?";
               pstm = con.prepareStatement(sql);
               pstm.setString(1,jComboClientes.getSelectedItem().toString());
               rs = pstm.executeQuery();
               while(rs.next()){
                   Idcliente = rs.getInt("idCliente");
                   clienteNome = rs.getString("nome");
                   idContacto = rs.getInt("Contacto_idContacto");
                   idIdentificacao = rs.getInt("Identificacao_idIdentificacao");
               }
     
               String tel ="";
               String cell ="";
               sql = "Select * from contacto where idContacto = ?";
               pstm = con.prepareStatement(sql);
               pstm.setInt(1,idContacto);
               rs = pstm.executeQuery();
               while(rs.next()){
                   tel = rs.getString("telefone");
                   cell = rs.getString("celular");
               }
               res.setCelular(cell);
               res.setTelefone(tel);
               
               
               String tipoID="";
               String numeroID ="";
               sql = "Select * from identificacao where idIdentificacao = ?";
               pstm = con.prepareStatement(sql);
               pstm.setInt(1,idIdentificacao);
               rs = pstm.executeQuery();
               while(rs.next()){
                   tipoID = rs.getString("tipoIdentificacao");
                   numeroID = rs.getString("numeroIdentificacao");
               }
               res.setTipoIdentificacao(tipoID);
               res.setNumeroIdentificacao(numeroID);
               
           } catch (SQLException ex) {
               Logger.getLogger(JIFReservas.class.getName()).log(Level.SEVERE, null, ex);
           }
           
       }
       res.setNomeCliente(txtNomeCliente.getText());
       DBConnector.actualizar(res);
       listarReservas();
       jButton1.setEnabled(true);
            txtCelular.setText("");
            txtNomeCliente.setText("");
            txtNrIdentificacao.setText("");
            txtObservacoes.setText("");
            txtPreco.setText("");
            txtTelefone.setText("");
            jDateData.setDate(null);
            jTimeHoraFinal.getTimeField().setText("00:00");
            jTimeHoraInicial.getTimeField().setText("00:00");
       
    }//GEN-LAST:event_jButton4ActionPerformed

    private void txtNrIdentificacaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNrIdentificacaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNrIdentificacaoActionPerformed

    /**
     * @param args the command line arguments
     */
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.toedter.calendar.DateUtil dateUtil1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JComboBox jComboClientes;
    private javax.swing.JComboBox jComboTipoID;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private com.toedter.calendar.JDateChooser jDateData;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinnerAcompanhantes;
    private javax.swing.JSpinner jSpinnerMesasOcupadas;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeHoraFinal;
    private lu.tudor.santec.jtimechooser.JTimeChooser jTimeHoraInicial;
    private javax.swing.JTable tableReservas;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtNomeCliente;
    private javax.swing.JTextField txtNrIdentificacao;
    private javax.swing.JTextArea txtObservacoes;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtTelefone;
    // End of variables declaration//GEN-END:variables
}
