/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantePOS;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import models.Categoriapratos;
import models.Categoriaproduto;
import models.Cliente;
import models.Fornecedores;
import models.Produtos;
import net.proteanit.sql.DbUtils;
import org.hibernate.Session;
import util.DBConnector;

/**
 *
 * @author Mr.Belton
 */
public class JIFStock extends javax.swing.JInternalFrame {

    /**
     * Creates new form JIFStockk
     */
      ArrayList<Fornecedores> f = null;
      ArrayList<Categoriaproduto> p = null; 
      static Session sessao; 
      private PreparedStatement pstm = null;
    private Connection con = null;
    private ResultSet rs = null;
    private Statement st;
      
    
    public JIFStock() {
        super("Gestao de Stock");
        initComponents();
        setClosable(true);
        conectar();
        listarProdutos();
        
   
            f = (ArrayList<Fornecedores>) DBConnector.buscarTodos(Fornecedores.class);
         
        for(int i=0; i<f.size(); i++){
            jComboFornecedor.addItem(f.get(i).getNome());
        }
        
         p = (ArrayList<Categoriaproduto>) DBConnector.buscarTodos(Categoriaproduto.class);
         for(int i=0; i<p.size(); i++){
            jComboCategoriaProduto.addItem(p.get(i).getNome());
        }
        
    }
    
    
     public void conectar(){
        try{
            Class.forName("com.mysql.jdbc.Driver");
            con = DriverManager.getConnection("jdbc:mysql://localhost:3306/sgrestaurante","root","");
          st=con.createStatement();
        }catch(Exception e){
            JOptionPane.showMessageDialog(null,e);
        }
     }
    
     public void pesquisaNaTabela(){
           String sql= "Select produtos.idProduto, produtos.nomeProduto, produtos.quantidade, produtos.codigoBarras, produtos.necessidade from produtos where nomeProduto like ?";
        try {
            pstm = con.prepareStatement(sql);
            pstm.setString(1, txtPesquisa.getText()+"%");
            rs = pstm.executeQuery();
            tableProdutos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(JIFFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
     }
     
    public void listarProdutos(){
        String sql= "Select produtos.idProduto, produtos.nomeProduto, produtos.quantidade, produtos.codigoBarras, produtos.necessidade from produtos";
        try {
            pstm = con.prepareStatement(sql);
            rs = pstm.executeQuery();
            tableProdutos.setModel(DbUtils.resultSetToTableModel(rs));
        } catch (SQLException ex) {
            Logger.getLogger(JIFFornecedores.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel11 = new javax.swing.JLabel();
        jComboBox7 = new javax.swing.JComboBox();
        jPanel1 = new javax.swing.JPanel();
        txtNome = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txtQuant = new javax.swing.JTextField();
        jComboUnidadeMedida = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jComboCategoriaProduto = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        txtQuantMin = new javax.swing.JTextField();
        jComboUnidadeMedidaMin = new javax.swing.JComboBox();
        jLabel6 = new javax.swing.JLabel();
        txtQuantMax = new javax.swing.JTextField();
        jComboUnidadeMedidaMax = new javax.swing.JComboBox();
        jLabel7 = new javax.swing.JLabel();
        txtPreco = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jComboNecessidade = new javax.swing.JComboBox();
        jLabel12 = new javax.swing.JLabel();
        txtCodigoBarras = new javax.swing.JTextField();
        jComboFornecedor = new javax.swing.JComboBox();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableProdutos = new javax.swing.JTable();
        txtPesquisa = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jComboBox6 = new javax.swing.JComboBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel11.setText("Listar por categoria");

        jComboBox7.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Registro de produtos"));

        txtNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNomeActionPerformed(evt);
            }
        });

        jLabel3.setText("Produto");

        jLabel4.setText("Quantidade");

        txtQuant.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtQuantActionPerformed(evt);
            }
        });

        jComboUnidadeMedida.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "T", "l" }));
        jComboUnidadeMedida.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUnidadeMedidaActionPerformed(evt);
            }
        });

        jLabel1.setText("Fornecedor");

        jLabel2.setText("Categoria");

        jComboCategoriaProduto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboCategoriaProdutoActionPerformed(evt);
            }
        });

        jLabel5.setText("Min");

        jComboUnidadeMedidaMin.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "T", "l" }));
        jComboUnidadeMedidaMin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUnidadeMedidaMinActionPerformed(evt);
            }
        });

        jLabel6.setText("Max");

        jComboUnidadeMedidaMax.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "kg", "T", "l" }));
        jComboUnidadeMedidaMax.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboUnidadeMedidaMaxActionPerformed(evt);
            }
        });

        jLabel7.setText("Preco unitario");

        jLabel8.setText("MT");

        jLabel9.setText("Necessidade do produto");

        jComboNecessidade.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Essencial", "Nao essencial" }));

        jLabel12.setText("Codigo de barras");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNome)
                            .addComponent(jComboFornecedor, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboNecessidade, 0, 135, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantMin, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboUnidadeMedidaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtQuantMax, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboUnidadeMedidaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(txtQuant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboUnidadeMedida, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jComboCategoriaProduto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtQuantMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboUnidadeMedidaMin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(txtQuantMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboUnidadeMedidaMax, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel7)
                    .addComponent(txtPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel12)
                    .addComponent(txtCodigoBarras, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboFornecedor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jComboNecessidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de produtos"));

        tableProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tableProdutos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tableProdutosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tableProdutos);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 312, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtPesquisa.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPesquisaKeyReleased(evt);
            }
        });

        jLabel13.setText("Pesquisa por nome");

        jLabel10.setText("Listar");

        jComboBox6.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todos", "Essencial", "Nao essencial" }));
        jComboBox6.setToolTipText("");

        jButton1.setText("Gravar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Limpar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Actualizar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Gerar lista de compras");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 6, Short.MAX_VALUE)
                        .addComponent(jLabel13)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(10, 10, 10)
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel11)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton5)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)
                        .addComponent(jLabel13)
                        .addComponent(txtPesquisa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel10)
                        .addComponent(jComboBox6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel11)
                        .addComponent(jComboBox7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNomeActionPerformed

    private void txtQuantActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtQuantActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtQuantActionPerformed

    private void jComboUnidadeMedidaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUnidadeMedidaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboUnidadeMedidaActionPerformed

    private void jComboUnidadeMedidaMinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUnidadeMedidaMinActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboUnidadeMedidaMinActionPerformed

    private void jComboUnidadeMedidaMaxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboUnidadeMedidaMaxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboUnidadeMedidaMaxActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
          try {
              ////////////////////////
              int idCategoria =0;
              String sql = "Select * from categoriaproduto where nome like ?";
              pstm = con.prepareStatement(sql);
              pstm.setString(1,jComboCategoriaProduto.getSelectedItem().toString());
              rs = pstm.executeQuery();
              while(rs.next()){
                  idCategoria = rs.getInt("idCategoriaProduto");
              }
              ///////////////////

              Categoriaproduto categoria = (Categoriaproduto) DBConnector.buscar(Categoriaproduto.class,idCategoria);
              
              ////////////////////////
              int idFornecedor =0;
              sql = "Select * from fornecedores where nome like ?";
              pstm = con.prepareStatement(sql);
              pstm.setString(1,jComboFornecedor.getSelectedItem().toString());
              rs = pstm.executeQuery();
              while(rs.next()){
                  idFornecedor = rs.getInt("idFornecedores");
              }
              ///////////////////
              
              Fornecedores fornecedores = (Fornecedores) DBConnector.buscar(Fornecedores.class,idFornecedor);
              
              DBConnector.salvar(new Produtos(categoria, fornecedores, txtNome.getText(),Double.parseDouble(txtQuant.getText()),Double.parseDouble(txtQuantMax.getText()),Double.parseDouble(txtQuantMin.getText()),txtCodigoBarras.getText(),Double.parseDouble(txtPreco.getText()),jComboNecessidade.getSelectedItem().toString(),jComboUnidadeMedida.getSelectedItem().toString(),jComboUnidadeMedidaMax.getSelectedItem().toString(),jComboUnidadeMedidaMin.getSelectedItem().toString()));
         
              listarProdutos();
          } catch (SQLException ex) {
              Logger.getLogger(JIFStock.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        jButton1.setEnabled(true);
        txtCodigoBarras.setText("");
       txtNome.setText("");
       txtPreco.setText("");
       txtQuant.setText("");
       txtQuantMax.setText("");
       txtQuantMin.setText("");
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
          if(tableProdutos.getSelectedRow() == -1){
           JOptionPane.showMessageDialog(null,"Seleccione o produto a ser removido!","Atencao",JOptionPane.WARNING_MESSAGE);
       }else{
           DBConnector.apagar(Produtos.class, (int) tableProdutos.getValueAt(tableProdutos.getSelectedRow(),0));
           listarProdutos();
       }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void tableProdutosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tableProdutosMouseClicked
          try {
              Produtos prod = (Produtos) DBConnector.buscar(Produtos.class, (int) tableProdutos.getValueAt(tableProdutos.getSelectedRow(), 0));

              int idCategoria =0;
              int idFornecedores=0;
              String sql = "Select * from produtos where idProduto = ?";
              pstm = con.prepareStatement(sql);
              pstm.setInt(1, (int) tableProdutos.getValueAt(tableProdutos.getSelectedRow(), 0));
              rs = pstm.executeQuery();
              while(rs.next()){
                  idCategoria = rs.getInt("CategoriaProduto_idCategoriaProduto");
                  idFornecedores = rs.getInt("Fornecedores_idFornecedores");
              }
              
              Categoriaproduto categoria = (Categoriaproduto) DBConnector.buscar(Categoriaproduto.class, idCategoria);
              Fornecedores fornecedor = (Fornecedores) DBConnector.buscar(Fornecedores.class,idFornecedores);
              
              
              jButton1.setEnabled(false);
              txtCodigoBarras.setText(prod.getCodigoBarras());
              txtNome.setText(prod.getNomeProduto());
              txtPreco.setText(""+prod.getPreco());
              txtQuantMax.setText(prod.getQuantMax()+"");
              txtQuantMin.setText(prod.getQuantMin()+"");
              txtQuant.setText(prod.getQuantidade()+"");
              jComboCategoriaProduto.setSelectedItem(categoria.getNome());
              jComboFornecedor.setSelectedItem(fornecedor.getNome());
              jComboNecessidade.setSelectedItem(prod.getNecessidade());
              jComboUnidadeMedida.setSelectedItem(prod.getUnidadeMedida());
              jComboUnidadeMedidaMax.setSelectedItem(prod.getUnidadeMedidaMax());
              jComboUnidadeMedidaMin.setSelectedItem(prod.getUnidadeMedidaMin());
          } catch (SQLException ex) {
              Logger.getLogger(JIFStock.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_tableProdutosMouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
          try {
              Produtos prod = (Produtos) DBConnector.buscar(Produtos.class, (int) tableProdutos.getValueAt(tableProdutos.getSelectedRow(), 0));
              
             
              
              prod.setCodigoBarras(txtCodigoBarras.getText());
              prod.setNecessidade(jComboNecessidade.getSelectedItem().toString());
              prod.setNomeProduto(txtNome.getText());
              prod.setPreco(Double.parseDouble(txtPreco.getText()));
              prod.setQuantMax(Double.parseDouble(txtQuantMax.getText()));
              prod.setQuantMin(Double.parseDouble(txtQuantMin.getText()));
              prod.setQuantidade(Double.parseDouble(txtQuant.getText()));
              prod.setUnidadeMedida(jComboUnidadeMedida.getSelectedItem().toString());
              prod.setUnidadeMedidaMax(jComboUnidadeMedidaMax.getSelectedItem().toString());
              prod.setUnidadeMedidaMin(jComboUnidadeMedidaMin.getSelectedItem().toString());
              
              ////////////////////////
              int idCategoria =0;
              String sql = "Select * from categoriaproduto where nome like ?";
              pstm = con.prepareStatement(sql);
              pstm.setString(1,jComboCategoriaProduto.getSelectedItem().toString());
              rs = pstm.executeQuery();
              while(rs.next()){
                  idCategoria = rs.getInt("idCategoriaProduto");
              }
              
              Categoriaproduto categoria = (Categoriaproduto) DBConnector.buscar(Categoriaproduto.class,idCategoria);
              prod.setCategoriaproduto(categoria);
             
              Connection conn = DriverManager.getConnection("jdbc:mysql://localhost:3306/sgrestaurante","root","");
            PreparedStatement st =(PreparedStatement) conn.prepareStatement("UPDATE `produtos` SET `CategoriaProduto_idCategoriaProduto`= '"+idCategoria+"' WHERE idProduto ='"+tableProdutos.getValueAt(tableProdutos.getSelectedRow(), 0)+"'");
                              st.executeUpdate(); 
              ///////////////////
              
             int idFornecedor =0;
              sql = "Select * from fornecedores where nome like ?";
              pstm = con.prepareStatement(sql);
              pstm.setString(1,jComboFornecedor.getSelectedItem().toString());
              rs = pstm.executeQuery();
              while(rs.next()){
                  idFornecedor = rs.getInt("idFornecedores");
              }
                              
             Fornecedores fornecedor = (Fornecedores) DBConnector.buscar(Fornecedores.class,idFornecedor);
              prod.setFornecedores(fornecedor);
            st =(PreparedStatement) conn.prepareStatement("UPDATE `produtos` SET `Fornecedores_idFornecedores`= '"+idFornecedor+"' WHERE idProduto ='"+tableProdutos.getValueAt(tableProdutos.getSelectedRow(), 0)+"'");
                              st.executeUpdate(); 
              
             
              DBConnector.actualizar(prod);
              listarProdutos();
              jButton1.setEnabled(true);
          } catch (SQLException ex) {
              Logger.getLogger(JIFStock.class.getName()).log(Level.SEVERE, null, ex);
          }
      
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboCategoriaProdutoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboCategoriaProdutoActionPerformed
          try {
              f = (ArrayList<Fornecedores>) DBConnector.buscarTodos(Fornecedores.class);
              jComboFornecedor.removeAllItems();
              
              
              ///////////////////////
              int idCategoria =0;
              String sql = "Select * from categoriaproduto where nome like ?";
              pstm = con.prepareStatement(sql);
              pstm.setString(1,jComboCategoriaProduto.getSelectedItem().toString());
              rs = pstm.executeQuery();
              while(rs.next()){
                  idCategoria = rs.getInt("idCategoriaProduto");
              }
              for(int i=0; i<f.size(); i++){
              Categoriaproduto cat = (Categoriaproduto) DBConnector.buscar(Categoriaproduto.class, f.get(i).getCategoriaproduto().getIdCategoriaProduto());
              
                  if(cat.getNome().equals(jComboCategoriaProduto.getSelectedItem().toString()))
                      jComboFornecedor.addItem(f.get(i).getNome());
                  ///////////////////
                  
                  
              } } catch (SQLException ex) {
              Logger.getLogger(JIFStock.class.getName()).log(Level.SEVERE, null, ex);
          }
    }//GEN-LAST:event_jComboCategoriaProdutoActionPerformed

    private void txtPesquisaKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPesquisaKeyReleased
       pesquisaNaTabela();
    }//GEN-LAST:event_txtPesquisaKeyReleased

    /**
     * @param args the command line arguments
     */
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JComboBox jComboBox6;
    private javax.swing.JComboBox jComboBox7;
    private javax.swing.JComboBox jComboCategoriaProduto;
    private javax.swing.JComboBox jComboFornecedor;
    private javax.swing.JComboBox jComboNecessidade;
    private javax.swing.JComboBox jComboUnidadeMedida;
    private javax.swing.JComboBox jComboUnidadeMedidaMax;
    private javax.swing.JComboBox jComboUnidadeMedidaMin;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tableProdutos;
    private javax.swing.JTextField txtCodigoBarras;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtPesquisa;
    private javax.swing.JTextField txtPreco;
    private javax.swing.JTextField txtQuant;
    private javax.swing.JTextField txtQuantMax;
    private javax.swing.JTextField txtQuantMin;
    // End of variables declaration//GEN-END:variables
}
