/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package restaurantePOS;

import java.awt.Dimension;
import java.awt.Frame;
import java.awt.Insets;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.List;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.table.DefaultTableModel;
import models.Categoriapratos;
import models.Mesas;
import models.Pratos;
import models.Produtos;
import net.miginfocom.layout.CC;
import net.miginfocom.swing.MigLayout;
import org.hibernate.Session;
import org.hibernate.SessionFactory;
import org.hibernate.Transaction;
import util.DBConnector;
import util.HibernateUtil;

/**
 *
 * @author frankcumaio
 */
public class MenuVendas extends javax.swing.JFrame implements ActionListener {

    private JPanel painelProdutos = new javax.swing.JPanel();
    private JButton bt, btC;
    ArrayList<String> produtos = new ArrayList<>();
    ArrayList<Double> bebidasPreco = new ArrayList<>();
    ArrayList<Produtos> alguns = null;
    static Session sessao;
    private static SessionFactory factory;
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    Vector<String> columnNames = new Vector<String>();
    List <models.Pedidos> listaPedidos;
    List <Mesas> listaMesas;
    int idPrato;
    int auxTab = 0;
    int nl,lugares;
    int iCliente = 1;
    int idPedidos,idMesa;
    boolean troca = false;
    boolean SelecionarPrato = true;
    MenuMesas mM = new MenuMesas();
    

    public MenuVendas() throws Exception {
        initComponents();
        criaGui();
        //mM.botoes();
        this.lugares = mM.nLugares;
        JOptionPane.showMessageDialog(rootPane, lugares);
        pratos();

    }

    public void setnLugares(Integer nLugares) {
        this.nl = nLugares;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jDialog1 = new javax.swing.JDialog();
        jButton2 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jtVendas = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jlMesa = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        ScrollClientes = new javax.swing.JScrollPane();
        painelClientes = new javax.swing.JPanel();
        jButton3 = new javax.swing.JButton();
        jbPagar = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jbCancelar = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane2.setViewportView(jTable1);

        jDialog1.setLocation(new java.awt.Point(0, 0));
        jDialog1.setModal(true);
        jDialog1.setUndecorated(true);
        jDialog1.setResizable(false);
        jDialog1.setSize(new java.awt.Dimension(444, 299));

        jButton2.setText("Dividir Conta");
        jButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jPanel3.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 108, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        jButton5.setText("Factura");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("jButton6");

        jButton8.setText("jButton8");

        jButton9.setText("jButton9");

        jButton10.setText("jButton10");

        javax.swing.GroupLayout jDialog1Layout = new javax.swing.GroupLayout(jDialog1.getContentPane());
        jDialog1.getContentPane().setLayout(jDialog1Layout);
        jDialog1Layout.setHorizontalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jDialog1Layout.createSequentialGroup()
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 6, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jDialog1Layout.setVerticalGroup(
            jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jDialog1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jDialog1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        jTabbedPane1.setTabPlacement(javax.swing.JTabbedPane.LEFT);
        jScrollPane1.setViewportView(jTabbedPane1);
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        jtVendas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Cliente", "Quant.", "Design.", "Preco"
            }
        ));
        jScrollPane3.setViewportView(jtVendas);

        jLabel1.setText("Frank Cumaio");

        jLabel2.setText("Mesa:");

        jlMesa.setText("Mesa 1");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 227, Short.MAX_VALUE)
        );

        ScrollClientes.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_NEVER);

        painelClientes.setBorder(javax.swing.BorderFactory.createTitledBorder("Clientes"));

        javax.swing.GroupLayout painelClientesLayout = new javax.swing.GroupLayout(painelClientes);
        painelClientes.setLayout(painelClientesLayout);
        painelClientesLayout.setHorizontalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        painelClientesLayout.setVerticalGroup(
            painelClientesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        ScrollClientes.setViewportView(painelClientes);

        jButton3.setText("Enviar C.");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jbPagar.setText("Pagar");
        jbPagar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPagarActionPerformed(evt);
            }
        });

        jButton7.setText("Anular");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jbCancelar.setText("Cancelar");
        jbCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbCancelarActionPerformed(evt);
            }
        });

        jButton1.setText("Opcoes");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jlMesa)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jbPagar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(0, 0, Short.MAX_VALUE)
                                        .addComponent(jButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 95, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jbCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addComponent(ScrollClientes)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jlMesa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ScrollClientes, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbPagar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jbCancelar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 775, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }//GEN-END:initComponents

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        Object[] bts = {"Sim", "Nao"};
        if (jtVendas.getRowCount() > 0) {
            int limpas = JOptionPane.showOptionDialog(null, "Deseja anular o produto?", "Atencao", 0, JOptionPane.QUESTION_MESSAGE, null, bts, bts[0]);
            if (limpas == 0) {
                // produtos.remove(produtos.size()-1);
                data.remove(data.size() - 1);
                jtVendas.setModel(new DefaultTableModel(data, columnNames));
            }
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jbCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbCancelarActionPerformed
        try {
            new MenuMesas().show();
        } catch (Exception ex) {
            Logger.getLogger(MenuVendas.class.getName()).log(Level.SEVERE, null, ex);
        }
        dispose();
    }//GEN-LAST:event_jbCancelarActionPerformed
   public void UltimoId(){
  
           sessao = HibernateUtil.getSessionFactory().getCurrentSession();
           sessao.beginTransaction();
           listaPedidos = (List<models.Pedidos>) sessao.createQuery("From Pedidos").list();
           for (models.Pedidos alvo : listaPedidos) {
               idPedidos=alvo.getIdpedidos();
           }

           sessao.getTransaction().commit();
    }
  
    private void jbPagarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPagarActionPerformed
//UltimoId();
//JOptionPane.showMessageDialog(rootPane, idPedidos);
  

    }//GEN-LAST:event_jbPagarActionPerformed
  private void setDialogLocation(Frame f) {
        Rectangle r = f.getBounds();
        int x = r.x + (r.width - jDialog1.getSize().width) / 2;
        int y = r.y + (r.height - jDialog1.getSize().height) / 2;
        jDialog1.setLocation(x, y);
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        setDialogLocation(this);
        jDialog1.setVisible(true);
        //jDialog1.setLocationRelativeTo(this);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        jDialog1.dispose();

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
            for (int i = 0; i < jtVendas.getRowCount(); i++) {
            UltimoId();
            
             listaMesas = (List<Mesas>) sessao.createQuery("From Mesas where nomeMesa ='"+jlMesa.getText()+"'").list();
           for (Mesas alvo : listaMesas) {
               idMesa=alvo.getIdMesas();
           }
           
            int nCliente = (int) jtVendas.getValueAt(i, 0);
            String designacao = (String) jtVendas.getValueAt(i, 2);
            int quant = (int) jtVendas.getValueAt(i, 1);
            double preco = (double) jtVendas.getValueAt(i, 3);
            DBConnector.salvarPedido(new models.Pedidos(idPedidos+1, nCliente, designacao, quant, (long) preco, null));
      //DBConnector.salvar(new Cliente(contacto, identificacao, morada, nome, sexo));

            //DBConnector.salvar(new Pedidos(idPedidos,));
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void criaGui() throws Exception {
        
        columnNames.add("Cliente");
        columnNames.add("Quant.");
        columnNames.add("Design.");
        columnNames.add("Preco");
        //jTabbedPane1.remove(0);
//        jPanel6.show(false);
        Transaction tx = null;
        Session session = util.HibernateUtil.getSessionFactory().openSession();
        try {
            session.beginTransaction();
            List categorias = session.createQuery("from Categoriapratos").list();
            Iterator it = categorias.iterator();

            while (it.hasNext()) {
                Categoriapratos cp = (Categoriapratos) it.next();
                jTabbedPane1.addTab(cp.getNome(), criaPainelVazio());
            }
        } catch (Exception e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e.getMessage());
        }
        jTabbedPane1.addMouseListener(new MouseListener() {

            @Override
            public void mouseClicked(MouseEvent e) {
                produtos.clear();
                painelProdutos.removeAll();
                pratos();

            }

            @Override
            public void mousePressed(MouseEvent e) {
            }

            @Override
            public void mouseReleased(MouseEvent e) {
            }

            @Override
            public void mouseEntered(MouseEvent e) {
            }

            @Override
            public void mouseExited(MouseEvent e) {
            }
        });

    }

    private JPanel criaPainelVazio() {
        JPanel dummyPanel = new JPanel() {

            @Override
            public Dimension getPreferredSize() {
                return isPreferredSizeSet()
                        ? super.getPreferredSize() : new Dimension(200, 200);
            }
        };
        return dummyPanel;
    }

    public void pratos() {

        Transaction tx = null;
        Session session = util.HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        try {
            List cp = session.createQuery("from Categoriapratos where nome = '" + jTabbedPane1.getTitleAt(jTabbedPane1.getSelectedIndex()) + "'").list();
            Iterator i = cp.iterator();

            while (i.hasNext()) {
                Categoriapratos c = (Categoriapratos) i.next();
                idPrato = c.getIdCategoriaPratos();

            }
            List listaProdutos = session.createQuery("from Pratos where CategoriaPratos_idCategoriaPratos = '" + idPrato + "'").list();
            Iterator it = listaProdutos.iterator();

            while (it.hasNext()) {
                Pratos p = (Pratos) it.next();
                produtos.add(p.getNome());
                bebidasPreco.add(p.getPreco());
            }
            botoes();
        } catch (Exception e) {
            if (tx != null) {
                tx.rollback();
            }
            System.out.println(e.getMessage());
        }
        //JOptionPane.showMessageDialog(rootPane, nl);
    }

    public void botoes() throws Exception {
        painelProdutos.setLayout(new MigLayout());
        for (int i = 0; i < produtos.size(); i++) {
            bt = new JButton(produtos.get(i));
            bt.setName("bt" + produtos.get(i));
            bt.setPreferredSize(new Dimension(150, 50));
            CC lCC = new CC();
            if ((i + 1) % 3 == 0) {
                lCC = lCC.wrap();
            }
            painelProdutos.add(bt, lCC);
            jTabbedPane1.setComponentAt(auxTab, criaPainelVazio());
            jTabbedPane1.setComponentAt(jTabbedPane1.getSelectedIndex(), painelProdutos);
            bt.addActionListener(this);
            auxTab = jTabbedPane1.getSelectedIndex();

        }
        
        
        painelClientes.setLayout(new MigLayout());
        for (int i = 0; i < lugares; i++) {
            int p = 1;
            p += i;
            btC = new JButton("" + p);
            btC.setName("bt" + p);
            btC.setPreferredSize(new Dimension(50, 40));
            painelClientes.add(btC);

            btC.addActionListener(new ActionListener() {

                @Override
                public void actionPerformed(ActionEvent e) {
                    JButton alvo = (JButton) e.getSource();
                    iCliente = Integer.parseInt(alvo.getText());
                    for (int j = 0; j < jtVendas.getRowCount(); j++) {
                        if (iCliente == Integer.parseInt(jtVendas.getValueAt(j, 0).toString())) {
                            troca = false;
                        } else {
                            troca = true;
                        }
                    }

                    //JOptionPane.showMessageDialog(rootPane,"ya");
                }
            });

        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    UIManager.getLookAndFeelDefaults().put("TabbedPane:TabbedPaneTab.contentMargins", new Insets(10, 100, 0, 0));

                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuVendas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuVendas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MenuVendas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane ScrollClientes;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JDialog jDialog1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbCancelar;
    private javax.swing.JButton jbPagar;
    private javax.swing.JLabel jlMesa;
    private javax.swing.JTable jtVendas;
    private javax.swing.JPanel painelClientes;
    // End of variables declaration//GEN-END:variables
@Override
    public void actionPerformed(ActionEvent e) {
        JButton alvo = (JButton) e.getSource();
        //JButton alvo2=(JButton)e.getSource();

       int pos = 0;
    boolean add = true;
    Vector<Object> vectorProdutos = new Vector<Object>();
    if (troca == false) {
        for (int i = 0; i < produtos.size(); i++) {
            if (produtos.get(i).equals(alvo.getText())) {
                for (int j = 0; j < jtVendas.getRowCount(); j++) {
                    if (produtos.get(i).equals(jtVendas.getValueAt(j, 2)) && iCliente == Integer.parseInt(jtVendas.getValueAt(j, 0).toString())) {
                        int up = (int) jtVendas.getValueAt(j, 1) + 1;

                        jtVendas.setValueAt(up, j, 1);
                        add = false;
                        troca = false;
                    }
                }
                if (add == true) {
                    vectorProdutos.add(iCliente);
                    vectorProdutos.add(1);
                    vectorProdutos.add(alvo.getText());
                    vectorProdutos.add(bebidasPreco.get(i));
                    data.add(vectorProdutos);
                    jtVendas.setModel(new DefaultTableModel(data, columnNames));
                }
            }
        }

        } else {
            add = true;
            for (int i = 0; i < produtos.size(); i++) {
                if (produtos.get(i).equals(alvo.getText())) {
                    for (int j = 0; j < jtVendas.getRowCount(); j++) {
                        if ((int) jtVendas.getValueAt(j, 0) == iCliente) {
                            if (produtos.get(i).equals(jtVendas.getValueAt(j, 2))) {
                                int up = (int) jtVendas.getValueAt(j, 1) + 1;

                                jtVendas.setValueAt(up, j, 1);
                                add = false;
                            }
                        }

                    }
                    if (add == true) {
                        vectorProdutos.add(iCliente);
                        vectorProdutos.add(1);
                        vectorProdutos.add(alvo.getText());
                        vectorProdutos.add(bebidasPreco.get(i));
                        data.add(vectorProdutos);
                        jtVendas.setModel(new DefaultTableModel(data, columnNames));
                    }

                }

            }

        }

    }
}
