package restaurantePOS;
import java.awt.Dimension;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.Calendar;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import models.Mesas;
import net.miginfocom.layout.CC;
import net.miginfocom.swing.MigLayout;
import org.hibernate.Session;
import org.hibernate.Transaction;
/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Frank Cumaio
 */
public class MenuMesas extends javax.swing.JFrame implements ActionListener {
int idMesa;
static public int nLugares;
ArrayList<String> mesa = new ArrayList<>();
ArrayList<Mesas> mesas = new ArrayList<Mesas>();
    /**
     * Creates new form Mesas
     */
    public MenuMesas() throws Exception {
        initComponents();
        botoes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {//GEN-BEGIN:initComponents

        jLabel1 = new javax.swing.JLabel();
        lblData = new javax.swing.JLabel();
        lblHora = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        rbLivres = new javax.swing.JRadioButton();
        rbOucupadas = new javax.swing.JRadioButton();
        rbReservadas = new javax.swing.JRadioButton();
        jPanel2 = new javax.swing.JPanel();
        jbPedidos = new javax.swing.JButton();
        jButton22 = new javax.swing.JButton();
        jButton23 = new javax.swing.JButton();
        jbSair = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jspMesas = new javax.swing.JScrollPane();
        painelMesas = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jLabel1.setText("Usuario Logado ");

        lblData.setText("12/08/2015");

        lblHora.setText("12:30");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ordenar por:"));

        rbLivres.setText("Livres");
        rbLivres.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbLivresMouseClicked(evt);
            }
        });
        rbLivres.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbLivresActionPerformed(evt);
            }
        });

        rbOucupadas.setText("Oucupadas");
        rbOucupadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbOucupadasMouseClicked(evt);
            }
        });

        rbReservadas.setText("Reservadas");
        rbReservadas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                rbReservadasMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(rbLivres)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbOucupadas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(rbReservadas)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rbOucupadas)
                    .addComponent(rbReservadas)
                    .addComponent(rbLivres))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Sistema"));

        jbPedidos.setText("Pedidos");
        jbPedidos.setMinimumSize(new java.awt.Dimension(90, 80));
        jbPedidos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbPedidosActionPerformed(evt);
            }
        });

        jButton22.setText("Reservas");
        jButton22.setMinimumSize(new java.awt.Dimension(90, 80));

        jButton23.setText("Trancar");
        jButton23.setMinimumSize(new java.awt.Dimension(90, 80));
        jButton23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton23ActionPerformed(evt);
            }
        });

        jbSair.setText("Sair");
        jbSair.setMaximumSize(new java.awt.Dimension(90, 80));
        jbSair.setMinimumSize(new java.awt.Dimension(90, 80));
        jbSair.setPreferredSize(new java.awt.Dimension(90, 80));
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jbPedidos, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton22, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton23, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(9, 9, 9))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton23, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbSair, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jbPedidos, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton22, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/restaurantePOS/imagem.jpg"))); // NOI18N

        jspMesas.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);

        javax.swing.GroupLayout painelMesasLayout = new javax.swing.GroupLayout(painelMesas);
        painelMesas.setLayout(painelMesasLayout);
        painelMesasLayout.setHorizontalGroup(
            painelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1084, Short.MAX_VALUE)
        );
        painelMesasLayout.setVerticalGroup(
            painelMesasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 314, Short.MAX_VALUE)
        );

        jspMesas.setViewportView(painelMesas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblData)
                            .addComponent(lblHora)
                            .addComponent(jLabel1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 88, Short.MAX_VALUE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addContainerGap())))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jspMesas)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblData)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblHora))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 329, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(145, Short.MAX_VALUE)
                    .addComponent(jspMesas, javax.swing.GroupLayout.PREFERRED_SIZE, 316, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(148, Short.MAX_VALUE)))
        );

        pack();
    }//GEN-END:initComponents

    private void jButton23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton23ActionPerformed
        new Login().setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton23ActionPerformed

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
    System.exit(0);
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbPedidosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbPedidosActionPerformed
    new MenuPedidos().show();
       dispose();
      
    }//GEN-LAST:event_jbPedidosActionPerformed

    private void rbLivresActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbLivresActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbLivresActionPerformed

    private void rbLivresMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbLivresMouseClicked
       rbOucupadas.setSelected(false);
       rbReservadas.setSelected(false);
    }//GEN-LAST:event_rbLivresMouseClicked

    private void rbOucupadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbOucupadasMouseClicked
       rbLivres.setSelected(false);
       rbReservadas.setSelected(false);
    }//GEN-LAST:event_rbOucupadasMouseClicked

    private void rbReservadasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_rbReservadasMouseClicked
        rbOucupadas.setSelected(false);
       rbLivres.setSelected(false);
    }//GEN-LAST:event_rbReservadasMouseClicked
   public void botoes() throws Exception{
       
   Timer  timer = new Timer(1000, new hora());
   timer.start(); 
   lblData.setText(new SimpleDateFormat("dd-MMM-YYYY").format(new Date()));
       
        Transaction tx = null;
        Session session = util.HibernateUtil.getSessionFactory().openSession();
        session.beginTransaction();

        try {
      
        List listaMesas = session.createQuery("from Mesas").list();
        Iterator it = listaMesas.iterator();

        while(it.hasNext()){
        Mesas m = (Mesas)it.next();
        mesas.add(m);
        mesa.add(m.getNomeMesa());
        }
           // JOptionPane.showMessageDialog(null, mesa);
        }
        catch(Exception e) {
        if(tx != null)
        tx.rollback();
        System.out.println(e.getMessage());
        }
        painelMesas.setLayout(new MigLayout());
        for(int i=0;i<mesa.size();i++){ 
        JButton bt = new JButton(mesa.get(i));
        bt.setName("bt"+mesa.get(i));
        bt.setPreferredSize(new Dimension(102, 100));
        CC lCC = new CC();
        if ((i + 1) % 10 == 0)
    {
        lCC = lCC.wrap();
    }
        painelMesas.add(bt,lCC);
        
       bt.addActionListener(this); 
       
        
       }
        }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("GTK+".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuMesas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
      
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new MenuMesas().setVisible(true);
                } catch (Exception ex) {
                    Logger.getLogger(MenuMesas.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }
    
     public void actionPerformed(ActionEvent e){
         JButton alvo=(JButton)e.getSource(); 
    try {
        new MenuVendas().show();
    } catch (Exception ex) {
        Logger.getLogger(MenuMesas.class.getName()).log(Level.SEVERE, null, ex);
    }
         dispose();
         for (int i=0;i<mesa.size();i++){
    if(mesa.get(i).equals(alvo.getText())){
        idMesa=mesas.get(i).getIdMesas();
        nLugares=mesas.get(i).getNumeroLugares();
    }}
         JOptionPane.showMessageDialog(rootPane, nLugares);
     }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton22;
    private javax.swing.JButton jButton23;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JButton jbPedidos;
    private javax.swing.JButton jbSair;
    private javax.swing.JScrollPane jspMesas;
    public static javax.swing.JLabel lblData;
    public static javax.swing.JLabel lblHora;
    private javax.swing.JPanel painelMesas;
    private javax.swing.JRadioButton rbLivres;
    private javax.swing.JRadioButton rbOucupadas;
    private javax.swing.JRadioButton rbReservadas;
    // End of variables declaration//GEN-END:variables
  public int getnLugares() {
     return this.nLugares;
  }
class hora implements ActionListener{

        @Override
        public void actionPerformed(ActionEvent e) {
            Calendar now = Calendar.getInstance();
            lblHora.setText(String.format("%1$tH:%1$tM:%1$tS",now));
        }
      
  }
}
