package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoriapratos generated by hbm2java
 */
@Entity
@Table(name="categoriapratos"
    ,catalog="sgrestaurante"
)
public class Categoriapratos  implements java.io.Serializable {


     private Integer idCategoriaPratos;
     private String nome;
     private Set<Pratos> pratoses = new HashSet<Pratos>(0);

    public Categoriapratos() {
    }

	
    public Categoriapratos(String nome) {
        this.nome = nome;
    }
    public Categoriapratos(String nome, Set<Pratos> pratoses) {
       this.nome = nome;
       this.pratoses = pratoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCategoriaPratos", unique=true, nullable=false)
    public Integer getIdCategoriaPratos() {
        return this.idCategoriaPratos;
    }
    
    public void setIdCategoriaPratos(Integer idCategoriaPratos) {
        this.idCategoriaPratos = idCategoriaPratos;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoriapratos")
    public Set<Pratos> getPratoses() {
        return this.pratoses;
    }
    
    public void setPratoses(Set<Pratos> pratoses) {
        this.pratoses = pratoses;
    }




}


