package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Categoriaproduto generated by hbm2java
 */
@Entity
@Table(name="categoriaproduto"
    ,catalog="sgrestaurante"
)
public class Categoriaproduto  implements java.io.Serializable {


     private Integer idCategoriaProduto;
     private String nome;
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);
     private Set<Fornecedores> fornecedoreses = new HashSet<Fornecedores>(0);

    public Categoriaproduto() {
    }

	
    public Categoriaproduto(String nome) {
        this.nome = nome;
    }
    public Categoriaproduto(String nome, Set<Produtos> produtoses, Set<Fornecedores> fornecedoreses) {
       this.nome = nome;
       this.produtoses = produtoses;
       this.fornecedoreses = fornecedoreses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idCategoriaProduto", unique=true, nullable=false)
    public Integer getIdCategoriaProduto() {
        return this.idCategoriaProduto;
    }
    
    public void setIdCategoriaProduto(Integer idCategoriaProduto) {
        this.idCategoriaProduto = idCategoriaProduto;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoriaproduto")
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="categoriaproduto")
    public Set<Fornecedores> getFornecedoreses() {
        return this.fornecedoreses;
    }
    
    public void setFornecedoreses(Set<Fornecedores> fornecedoreses) {
        this.fornecedoreses = fornecedoreses;
    }




}


