package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Contacto generated by hbm2java
 */
@Entity
@Table(name="contacto"
    ,catalog="sgrestaurante"
    , uniqueConstraints = {@UniqueConstraint(columnNames="celular"), @UniqueConstraint(columnNames="email"), @UniqueConstraint(columnNames="telefone")} 
)
public class Contacto  implements java.io.Serializable {


     private Integer idContacto;
     private String telefone;
     private String celular;
     private String email;
     private Set<Fornecedores> fornecedoreses = new HashSet<Fornecedores>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Funcionarios> funcionarioses = new HashSet<Funcionarios>(0);

    public Contacto() {
    }

    public Contacto(String telefone, String celular, String email, Set<Fornecedores> fornecedoreses, Set<Cliente> clientes, Set<Funcionarios> funcionarioses) {
       this.telefone = telefone;
       this.celular = celular;
       this.email = email;
       this.fornecedoreses = fornecedoreses;
       this.clientes = clientes;
       this.funcionarioses = funcionarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idContacto", unique=true, nullable=false)
    public Integer getIdContacto() {
        return this.idContacto;
    }
    
    public void setIdContacto(Integer idContacto) {
        this.idContacto = idContacto;
    }

    
    @Column(name="telefone", unique=true, length=45)
    public String getTelefone() {
        return this.telefone;
    }
    
    public void setTelefone(String telefone) {
        this.telefone = telefone;
    }

    
    @Column(name="celular", unique=true, length=45)
    public String getCelular() {
        return this.celular;
    }
    
    public void setCelular(String celular) {
        this.celular = celular;
    }

    
    @Column(name="email", unique=true)
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contacto")
    public Set<Fornecedores> getFornecedoreses() {
        return this.fornecedoreses;
    }
    
    public void setFornecedoreses(Set<Fornecedores> fornecedoreses) {
        this.fornecedoreses = fornecedoreses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contacto")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="contacto")
    public Set<Funcionarios> getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set<Funcionarios> funcionarioses) {
        this.funcionarioses = funcionarioses;
    }




}


