package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Fornecedores generated by hbm2java
 */
@Entity
@Table(name="fornecedores"
    ,catalog="sgrestaurante"
)
public class Fornecedores  implements java.io.Serializable {


     private Integer idFornecedores;
     private Categoriaproduto categoriaproduto;
     private Contacto contacto;
     private Morada morada;
     private String nome;
     private String nrRegisto;
     private String tipoProduto;
     private String observacoes;
     private Double distancia;
     private String unidadeMedida;
     private Set<Produtos> produtoses = new HashSet<Produtos>(0);

    public Fornecedores() {
    }

	
    public Fornecedores(Categoriaproduto categoriaproduto, Contacto contacto, Morada morada, String nome, String nrRegisto, String tipoProduto) {
        this.categoriaproduto = categoriaproduto;
        this.contacto = contacto;
        this.morada = morada;
        this.nome = nome;
        this.nrRegisto = nrRegisto;
        this.tipoProduto = tipoProduto;
    }
    public Fornecedores(Categoriaproduto categoriaproduto, Contacto contacto, Morada morada, String nome, String nrRegisto, String tipoProduto, String observacoes, Double distancia, String unidadeMedida, Set<Produtos> produtoses) {
       this.categoriaproduto = categoriaproduto;
       this.contacto = contacto;
       this.morada = morada;
       this.nome = nome;
       this.nrRegisto = nrRegisto;
       this.tipoProduto = tipoProduto;
       this.observacoes = observacoes;
       this.distancia = distancia;
       this.unidadeMedida = unidadeMedida;
       this.produtoses = produtoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFornecedores", unique=true, nullable=false)
    public Integer getIdFornecedores() {
        return this.idFornecedores;
    }
    
    public void setIdFornecedores(Integer idFornecedores) {
        this.idFornecedores = idFornecedores;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoriaProduto_idCategoriaProduto", nullable=false)
    public Categoriaproduto getCategoriaproduto() {
        return this.categoriaproduto;
    }
    
    public void setCategoriaproduto(Categoriaproduto categoriaproduto) {
        this.categoriaproduto = categoriaproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Contacto_idContacto", nullable=false)
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Morada_idMorada", nullable=false)
    public Morada getMorada() {
        return this.morada;
    }
    
    public void setMorada(Morada morada) {
        this.morada = morada;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="nrRegisto", nullable=false)
    public String getNrRegisto() {
        return this.nrRegisto;
    }
    
    public void setNrRegisto(String nrRegisto) {
        this.nrRegisto = nrRegisto;
    }

    
    @Column(name="tipoProduto", nullable=false)
    public String getTipoProduto() {
        return this.tipoProduto;
    }
    
    public void setTipoProduto(String tipoProduto) {
        this.tipoProduto = tipoProduto;
    }

    
    @Column(name="observacoes", length=45)
    public String getObservacoes() {
        return this.observacoes;
    }
    
    public void setObservacoes(String observacoes) {
        this.observacoes = observacoes;
    }

    
    @Column(name="distancia", precision=22, scale=0)
    public Double getDistancia() {
        return this.distancia;
    }
    
    public void setDistancia(Double distancia) {
        this.distancia = distancia;
    }

    
    @Column(name="unidadeMedida", length=45)
    public String getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(String unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="fornecedores")
    public Set<Produtos> getProdutoses() {
        return this.produtoses;
    }
    
    public void setProdutoses(Set<Produtos> produtoses) {
        this.produtoses = produtoses;
    }




}


