package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Funcionarios generated by hbm2java
 */
@Entity
@Table(name="funcionarios"
    ,catalog="sgrestaurante"
)
public class Funcionarios  implements java.io.Serializable {


     private Integer idFuncionario;
     private Contacto contacto;
     private Identificacao identificacao;
     private Morada morada;
     private String nome;
     private String sexo;
     private Date dataNascimento;
     private String cargo;
     private double salario;
     private Date dataIngresso;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Funcionarios() {
    }

	
    public Funcionarios(Contacto contacto, Identificacao identificacao, Morada morada, String nome, String sexo, Date dataNascimento, String cargo, double salario, Date dataIngresso) {
        this.contacto = contacto;
        this.identificacao = identificacao;
        this.morada = morada;
        this.nome = nome;
        this.sexo = sexo;
        this.dataNascimento = dataNascimento;
        this.cargo = cargo;
        this.salario = salario;
        this.dataIngresso = dataIngresso;
    }
    public Funcionarios(Contacto contacto, Identificacao identificacao, Morada morada, String nome, String sexo, Date dataNascimento, String cargo, double salario, Date dataIngresso, Set<Usuario> usuarios) {
       this.contacto = contacto;
       this.identificacao = identificacao;
       this.morada = morada;
       this.nome = nome;
       this.sexo = sexo;
       this.dataNascimento = dataNascimento;
       this.cargo = cargo;
       this.salario = salario;
       this.dataIngresso = dataIngresso;
       this.usuarios = usuarios;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idFuncionario", unique=true, nullable=false)
    public Integer getIdFuncionario() {
        return this.idFuncionario;
    }
    
    public void setIdFuncionario(Integer idFuncionario) {
        this.idFuncionario = idFuncionario;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Contacto_idContacto", nullable=false)
    public Contacto getContacto() {
        return this.contacto;
    }
    
    public void setContacto(Contacto contacto) {
        this.contacto = contacto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Identificacao_idIdentificacao", nullable=false)
    public Identificacao getIdentificacao() {
        return this.identificacao;
    }
    
    public void setIdentificacao(Identificacao identificacao) {
        this.identificacao = identificacao;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Morada_idMorada", nullable=false)
    public Morada getMorada() {
        return this.morada;
    }
    
    public void setMorada(Morada morada) {
        this.morada = morada;
    }

    
    @Column(name="nome", nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="sexo", nullable=false, length=45)
    public String getSexo() {
        return this.sexo;
    }
    
    public void setSexo(String sexo) {
        this.sexo = sexo;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataNascimento", nullable=false, length=10)
    public Date getDataNascimento() {
        return this.dataNascimento;
    }
    
    public void setDataNascimento(Date dataNascimento) {
        this.dataNascimento = dataNascimento;
    }

    
    @Column(name="cargo", nullable=false)
    public String getCargo() {
        return this.cargo;
    }
    
    public void setCargo(String cargo) {
        this.cargo = cargo;
    }

    
    @Column(name="salario", nullable=false, precision=10)
    public double getSalario() {
        return this.salario;
    }
    
    public void setSalario(double salario) {
        this.salario = salario;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataIngresso", nullable=false, length=10)
    public Date getDataIngresso() {
        return this.dataIngresso;
    }
    
    public void setDataIngresso(Date dataIngresso) {
        this.dataIngresso = dataIngresso;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="funcionarios")
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


