package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Identificacao generated by hbm2java
 */
@Entity
@Table(name="identificacao"
    ,catalog="sgrestaurante"
)
public class Identificacao  implements java.io.Serializable {


     private Integer idIdentificacao;
     private String tipoIdentificacao;
     private String numeroIdentificacao;
     private Date dataValidade;
     private Set<Funcionarios> funcionarioses = new HashSet<Funcionarios>(0);
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Identificacao() {
    }

	
    public Identificacao(String tipoIdentificacao, String numeroIdentificacao, Date dataValidade) {
        this.tipoIdentificacao = tipoIdentificacao;
        this.numeroIdentificacao = numeroIdentificacao;
        this.dataValidade = dataValidade;
    }
    public Identificacao(String tipoIdentificacao, String numeroIdentificacao, Date dataValidade, Set<Funcionarios> funcionarioses, Set<Cliente> clientes) {
       this.tipoIdentificacao = tipoIdentificacao;
       this.numeroIdentificacao = numeroIdentificacao;
       this.dataValidade = dataValidade;
       this.funcionarioses = funcionarioses;
       this.clientes = clientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idIdentificacao", unique=true, nullable=false)
    public Integer getIdIdentificacao() {
        return this.idIdentificacao;
    }
    
    public void setIdIdentificacao(Integer idIdentificacao) {
        this.idIdentificacao = idIdentificacao;
    }

    
    @Column(name="tipoIdentificacao", nullable=false)
    public String getTipoIdentificacao() {
        return this.tipoIdentificacao;
    }
    
    public void setTipoIdentificacao(String tipoIdentificacao) {
        this.tipoIdentificacao = tipoIdentificacao;
    }

    
    @Column(name="numeroIdentificacao", nullable=false)
    public String getNumeroIdentificacao() {
        return this.numeroIdentificacao;
    }
    
    public void setNumeroIdentificacao(String numeroIdentificacao) {
        this.numeroIdentificacao = numeroIdentificacao;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dataValidade", nullable=false, length=10)
    public Date getDataValidade() {
        return this.dataValidade;
    }
    
    public void setDataValidade(Date dataValidade) {
        this.dataValidade = dataValidade;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="identificacao")
    public Set<Funcionarios> getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set<Funcionarios> funcionarioses) {
        this.funcionarioses = funcionarioses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="identificacao")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


