package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Mesas generated by hbm2java
 */
@Entity
@Table(name="mesas"
    ,catalog="sgrestaurante"
    , uniqueConstraints = @UniqueConstraint(columnNames="nomeMesa") 
)
public class Mesas  implements java.io.Serializable {


     private Integer idMesas;
     private String nomeMesa;
     private int numeroLugares;
     private String descricao;
     private Set<Pedidos> pedidoses = new HashSet<Pedidos>(0);

    public Mesas() {
    }

	
    public Mesas(String nomeMesa, int numeroLugares, String descricao) {
        this.nomeMesa = nomeMesa;
        this.numeroLugares = numeroLugares;
        this.descricao = descricao;
    }
    public Mesas(String nomeMesa, int numeroLugares, String descricao, Set<Pedidos> pedidoses) {
       this.nomeMesa = nomeMesa;
       this.numeroLugares = numeroLugares;
       this.descricao = descricao;
       this.pedidoses = pedidoses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMesas", unique=true, nullable=false)
    public Integer getIdMesas() {
        return this.idMesas;
    }
    
    public void setIdMesas(Integer idMesas) {
        this.idMesas = idMesas;
    }

    
    @Column(name="nomeMesa", unique=true, nullable=false, length=45)
    public String getNomeMesa() {
        return this.nomeMesa;
    }
    
    public void setNomeMesa(String nomeMesa) {
        this.nomeMesa = nomeMesa;
    }

    
    @Column(name="numeroLugares", nullable=false)
    public int getNumeroLugares() {
        return this.numeroLugares;
    }
    
    public void setNumeroLugares(int numeroLugares) {
        this.numeroLugares = numeroLugares;
    }

    
    @Column(name="descricao", nullable=false)
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pedidos_has_mesas", catalog="sgrestaurante", joinColumns = { 
        @JoinColumn(name="mesas_idMesas", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="pedidos_idpedidos", nullable=false, updatable=false) })
    public Set<Pedidos> getPedidoses() {
        return this.pedidoses;
    }
    
    public void setPedidoses(Set<Pedidos> pedidoses) {
        this.pedidoses = pedidoses;
    }




}


