package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Morada generated by hbm2java
 */
@Entity
@Table(name="morada"
    ,catalog="sgrestaurante"
)
public class Morada  implements java.io.Serializable {


     private Integer idMorada;
     private String avRua;
     private String cidade;
     private String bairro;
     private int numero;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);
     private Set<Fornecedores> fornecedoreses = new HashSet<Fornecedores>(0);
     private Set<Funcionarios> funcionarioses = new HashSet<Funcionarios>(0);

    public Morada() {
    }

	
    public Morada(String cidade, String bairro, int numero) {
        this.cidade = cidade;
        this.bairro = bairro;
        this.numero = numero;
    }
    public Morada(String avRua, String cidade, String bairro, int numero, Set<Cliente> clientes, Set<Fornecedores> fornecedoreses, Set<Funcionarios> funcionarioses) {
       this.avRua = avRua;
       this.cidade = cidade;
       this.bairro = bairro;
       this.numero = numero;
       this.clientes = clientes;
       this.fornecedoreses = fornecedoreses;
       this.funcionarioses = funcionarioses;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idMorada", unique=true, nullable=false)
    public Integer getIdMorada() {
        return this.idMorada;
    }
    
    public void setIdMorada(Integer idMorada) {
        this.idMorada = idMorada;
    }

    
    @Column(name="AvRua")
    public String getAvRua() {
        return this.avRua;
    }
    
    public void setAvRua(String avRua) {
        this.avRua = avRua;
    }

    
    @Column(name="Cidade", nullable=false)
    public String getCidade() {
        return this.cidade;
    }
    
    public void setCidade(String cidade) {
        this.cidade = cidade;
    }

    
    @Column(name="Bairro", nullable=false)
    public String getBairro() {
        return this.bairro;
    }
    
    public void setBairro(String bairro) {
        this.bairro = bairro;
    }

    
    @Column(name="numero", nullable=false)
    public int getNumero() {
        return this.numero;
    }
    
    public void setNumero(int numero) {
        this.numero = numero;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="morada")
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="morada")
    public Set<Fornecedores> getFornecedoreses() {
        return this.fornecedoreses;
    }
    
    public void setFornecedoreses(Set<Fornecedores> fornecedoreses) {
        this.fornecedoreses = fornecedoreses;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="morada")
    public Set<Funcionarios> getFuncionarioses() {
        return this.funcionarioses;
    }
    
    public void setFuncionarioses(Set<Funcionarios> funcionarioses) {
        this.funcionarioses = funcionarioses;
    }




}


