package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.Table;

/**
 * Pedidos generated by hbm2java
 */
@Entity
@Table(name="pedidos"
    ,catalog="sgrestaurante"
)
public class Pedidos  implements java.io.Serializable {


     private int idpedidos;
     private int ncliente;
     private String designacao;
     private int quant;
     private long preco;
     private Set<Mesas> mesases = new HashSet<Mesas>(0);

    public Pedidos() {
    }

	
    public Pedidos(int idpedidos, int ncliente, String designacao, int quant, long preco) {
        this.idpedidos = idpedidos;
        this.ncliente = ncliente;
        this.designacao = designacao;
        this.quant = quant;
        this.preco = preco;
    }
    public Pedidos(int idpedidos, int ncliente, String designacao, int quant, long preco, Set<Mesas> mesases) {
       this.idpedidos = idpedidos;
       this.ncliente = ncliente;
       this.designacao = designacao;
       this.quant = quant;
       this.preco = preco;
       this.mesases = mesases;
    }
   
     @Id 

    
    @Column(name="idpedidos", unique=true, nullable=false)
    public int getIdpedidos() {
        return this.idpedidos;
    }
    
    public void setIdpedidos(int idpedidos) {
        this.idpedidos = idpedidos;
    }

    
    @Column(name="ncliente", nullable=false)
    public int getNcliente() {
        return this.ncliente;
    }
    
    public void setNcliente(int ncliente) {
        this.ncliente = ncliente;
    }

    
    @Column(name="designacao", nullable=false, length=45)
    public String getDesignacao() {
        return this.designacao;
    }
    
    public void setDesignacao(String designacao) {
        this.designacao = designacao;
    }

    
    @Column(name="quant", nullable=false)
    public int getQuant() {
        return this.quant;
    }
    
    public void setQuant(int quant) {
        this.quant = quant;
    }

    
    @Column(name="preco", nullable=false, precision=10, scale=0)
    public long getPreco() {
        return this.preco;
    }
    
    public void setPreco(long preco) {
        this.preco = preco;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="pedidos_has_mesas", catalog="sgrestaurante", joinColumns = { 
        @JoinColumn(name="pedidos_idpedidos", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="mesas_idMesas", nullable=false, updatable=false) })
    public Set<Mesas> getMesases() {
        return this.mesases;
    }
    
    public void setMesases(Set<Mesas> mesases) {
        this.mesases = mesases;
    }




}


