package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Pratos generated by hbm2java
 */
@Entity
@Table(name="pratos"
    ,catalog="sgrestaurante"
    , uniqueConstraints = @UniqueConstraint(columnNames="nome") 
)
public class Pratos  implements java.io.Serializable {


     private Integer idPratos;
     private Categoriapratos categoriapratos;
     private Ingredientes ingredientes;
     private IngredientesAux ingredientesAux;
     private String nome;
     private String categoria;
     private double preco;
     private String descricao;
     private int ingredientesId;

    public Pratos() {
    }

	
    public Pratos(Categoriapratos categoriapratos, String nome, String categoria, double preco, int ingredientesId) {
        this.categoriapratos = categoriapratos;
        this.nome = nome;
        this.categoria = categoria;
        this.preco = preco;
        this.ingredientesId = ingredientesId;
    }
    public Pratos(Categoriapratos categoriapratos, Ingredientes ingredientes, IngredientesAux ingredientesAux, String nome, String categoria, double preco, String descricao, int ingredientesId) {
       this.categoriapratos = categoriapratos;
       this.ingredientes = ingredientes;
       this.ingredientesAux = ingredientesAux;
       this.nome = nome;
       this.categoria = categoria;
       this.preco = preco;
       this.descricao = descricao;
       this.ingredientesId = ingredientesId;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idPratos", unique=true, nullable=false)
    public Integer getIdPratos() {
        return this.idPratos;
    }
    
    public void setIdPratos(Integer idPratos) {
        this.idPratos = idPratos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoriaPratos_idCategoriaPratos", nullable=false)
    public Categoriapratos getCategoriapratos() {
        return this.categoriapratos;
    }
    
    public void setCategoriapratos(Categoriapratos categoriapratos) {
        this.categoriapratos = categoriapratos;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ingredientes_codigo")
    public Ingredientes getIngredientes() {
        return this.ingredientes;
    }
    
    public void setIngredientes(Ingredientes ingredientes) {
        this.ingredientes = ingredientes;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="ingredientes_Aux_codigo")
    public IngredientesAux getIngredientesAux() {
        return this.ingredientesAux;
    }
    
    public void setIngredientesAux(IngredientesAux ingredientesAux) {
        this.ingredientesAux = ingredientesAux;
    }

    
    @Column(name="nome", unique=true, nullable=false)
    public String getNome() {
        return this.nome;
    }
    
    public void setNome(String nome) {
        this.nome = nome;
    }

    
    @Column(name="categoria", nullable=false)
    public String getCategoria() {
        return this.categoria;
    }
    
    public void setCategoria(String categoria) {
        this.categoria = categoria;
    }

    
    @Column(name="preco", nullable=false, precision=10)
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }

    
    @Column(name="descricao")
    public String getDescricao() {
        return this.descricao;
    }
    
    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    
    @Column(name="ingredientesId", nullable=false)
    public int getIngredientesId() {
        return this.ingredientesId;
    }
    
    public void setIngredientesId(int ingredientesId) {
        this.ingredientesId = ingredientesId;
    }




}


