package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.UniqueConstraint;

/**
 * Produtos generated by hbm2java
 */
@Entity
@Table(name="produtos"
    ,catalog="sgrestaurante"
    , uniqueConstraints = {@UniqueConstraint(columnNames="codigoBarras"), @UniqueConstraint(columnNames="nomeProduto")} 
)
public class Produtos  implements java.io.Serializable {


     private Integer idProduto;
     private Categoriaproduto categoriaproduto;
     private Fornecedores fornecedores;
     private String nomeProduto;
     private double quantidade;
     private double quantMax;
     private double quantMin;
     private String codigoBarras;
     private double preco;
     private String necessidade;
     private String unidadeMedida;
     private String unidadeMedidaMax;
     private String unidadeMedidaMin;

    public Produtos() {
    }

    public Produtos(Categoriaproduto categoriaproduto, Fornecedores fornecedores, String nomeProduto, double quantidade, double quantMax, double quantMin, String codigoBarras, double preco, String necessidade, String unidadeMedida, String unidadeMedidaMax, String unidadeMedidaMin) {
       this.categoriaproduto = categoriaproduto;
       this.fornecedores = fornecedores;
       this.nomeProduto = nomeProduto;
       this.quantidade = quantidade;
       this.quantMax = quantMax;
       this.quantMin = quantMin;
       this.codigoBarras = codigoBarras;
       this.preco = preco;
       this.necessidade = necessidade;
       this.unidadeMedida = unidadeMedida;
       this.unidadeMedidaMax = unidadeMedidaMax;
       this.unidadeMedidaMin = unidadeMedidaMin;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idProduto", unique=true, nullable=false)
    public Integer getIdProduto() {
        return this.idProduto;
    }
    
    public void setIdProduto(Integer idProduto) {
        this.idProduto = idProduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="CategoriaProduto_idCategoriaProduto", nullable=false)
    public Categoriaproduto getCategoriaproduto() {
        return this.categoriaproduto;
    }
    
    public void setCategoriaproduto(Categoriaproduto categoriaproduto) {
        this.categoriaproduto = categoriaproduto;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="Fornecedores_idFornecedores", nullable=false)
    public Fornecedores getFornecedores() {
        return this.fornecedores;
    }
    
    public void setFornecedores(Fornecedores fornecedores) {
        this.fornecedores = fornecedores;
    }

    
    @Column(name="nomeProduto", unique=true, nullable=false)
    public String getNomeProduto() {
        return this.nomeProduto;
    }
    
    public void setNomeProduto(String nomeProduto) {
        this.nomeProduto = nomeProduto;
    }

    
    @Column(name="quantidade", nullable=false, precision=22, scale=0)
    public double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="quantMax", nullable=false, precision=22, scale=0)
    public double getQuantMax() {
        return this.quantMax;
    }
    
    public void setQuantMax(double quantMax) {
        this.quantMax = quantMax;
    }

    
    @Column(name="quantMin", nullable=false, precision=22, scale=0)
    public double getQuantMin() {
        return this.quantMin;
    }
    
    public void setQuantMin(double quantMin) {
        this.quantMin = quantMin;
    }

    
    @Column(name="codigoBarras", unique=true, nullable=false, length=65)
    public String getCodigoBarras() {
        return this.codigoBarras;
    }
    
    public void setCodigoBarras(String codigoBarras) {
        this.codigoBarras = codigoBarras;
    }

    
    @Column(name="preco", nullable=false, precision=10)
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }

    
    @Column(name="necessidade", nullable=false, length=45)
    public String getNecessidade() {
        return this.necessidade;
    }
    
    public void setNecessidade(String necessidade) {
        this.necessidade = necessidade;
    }

    
    @Column(name="unidadeMedida", nullable=false, length=45)
    public String getUnidadeMedida() {
        return this.unidadeMedida;
    }
    
    public void setUnidadeMedida(String unidadeMedida) {
        this.unidadeMedida = unidadeMedida;
    }

    
    @Column(name="unidadeMedidaMax", nullable=false, length=45)
    public String getUnidadeMedidaMax() {
        return this.unidadeMedidaMax;
    }
    
    public void setUnidadeMedidaMax(String unidadeMedidaMax) {
        this.unidadeMedidaMax = unidadeMedidaMax;
    }

    
    @Column(name="unidadeMedidaMin", nullable=false, length=45)
    public String getUnidadeMedidaMin() {
        return this.unidadeMedidaMin;
    }
    
    public void setUnidadeMedidaMin(String unidadeMedidaMin) {
        this.unidadeMedidaMin = unidadeMedidaMin;
    }




}


