package models;
// Generated Sep 23, 2015 11:22:21 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Vendas generated by hbm2java
 */
@Entity
@Table(name="vendas"
    ,catalog="sgrestaurante"
)
public class Vendas  implements java.io.Serializable {


     private Integer idVendas;
     private Formaspagamento formaspagamento;
     private String cliente;
     private String produto;
     private double quantidade;
     private double preco;
     private Set<Cliente> clientes = new HashSet<Cliente>(0);

    public Vendas() {
    }

	
    public Vendas(Formaspagamento formaspagamento, String cliente, String produto, double quantidade, double preco) {
        this.formaspagamento = formaspagamento;
        this.cliente = cliente;
        this.produto = produto;
        this.quantidade = quantidade;
        this.preco = preco;
    }
    public Vendas(Formaspagamento formaspagamento, String cliente, String produto, double quantidade, double preco, Set<Cliente> clientes) {
       this.formaspagamento = formaspagamento;
       this.cliente = cliente;
       this.produto = produto;
       this.quantidade = quantidade;
       this.preco = preco;
       this.clientes = clientes;
    }
   
     @Id @GeneratedValue(strategy=IDENTITY)

    
    @Column(name="idVendas", unique=true, nullable=false)
    public Integer getIdVendas() {
        return this.idVendas;
    }
    
    public void setIdVendas(Integer idVendas) {
        this.idVendas = idVendas;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="FormasPagamento_idFormasPagamento", nullable=false)
    public Formaspagamento getFormaspagamento() {
        return this.formaspagamento;
    }
    
    public void setFormaspagamento(Formaspagamento formaspagamento) {
        this.formaspagamento = formaspagamento;
    }

    
    @Column(name="cliente", nullable=false)
    public String getCliente() {
        return this.cliente;
    }
    
    public void setCliente(String cliente) {
        this.cliente = cliente;
    }

    
    @Column(name="produto", nullable=false, length=45)
    public String getProduto() {
        return this.produto;
    }
    
    public void setProduto(String produto) {
        this.produto = produto;
    }

    
    @Column(name="quantidade", nullable=false, precision=22, scale=0)
    public double getQuantidade() {
        return this.quantidade;
    }
    
    public void setQuantidade(double quantidade) {
        this.quantidade = quantidade;
    }

    
    @Column(name="preco", nullable=false, precision=22, scale=0)
    public double getPreco() {
        return this.preco;
    }
    
    public void setPreco(double preco) {
        this.preco = preco;
    }

@ManyToMany(fetch=FetchType.LAZY)
    @JoinTable(name="vendas_has_cliente", catalog="sgrestaurante", joinColumns = { 
        @JoinColumn(name="Vendas_idVendas", nullable=false, updatable=false) }, inverseJoinColumns = { 
        @JoinColumn(name="Cliente_idCliente", nullable=false, updatable=false) })
    public Set<Cliente> getClientes() {
        return this.clientes;
    }
    
    public void setClientes(Set<Cliente> clientes) {
        this.clientes = clientes;
    }




}


